#!/usr/bin/expect

set timeout 60  ;

set start_time [clock seconds]

# Start the program
spawn java -jar ClientStart.jar


expect "Insert Port number:"
send "12345\r"

expect "Insert Max Requests:"
send "5\r"

expect "Insert Max Parallel:"
send "1\r"


expect "Select Request:"
send "10\r"

expect "Insert Username:"
send "TestClient\r"

expect "Insert Password:"
send "123\r"

expect "Select Test:"
send "2\r"

expect "Select Request:"
send "10\r"

expect "Insert Username:"
send "TestClient\r"

expect "Insert Password:"
send "123\r"

expect "Select Test:"
send "3\r"

expect "Select Request:"
send "10\r"

expect "Insert Username:"
send "TestClient\r"

expect "Insert Password:"
send "123\r"

expect "Select Test:"
send "1\r"

expect "3 Tests Done!"
send "9\r"   ;# Replace 'exit\r' with whatever ends the program cleanly if needed

set start_time_formatted [clock format $start_time -format "%Y-%m-%d %H:%M:%S"]
puts "Test started at: $start_time_formatted"

# Calculate and display elapsed time

set end_time [clock seconds]
set end_time_formatted [clock format $end_time -format "%Y-%m-%d %H:%M:%S"]
puts "Test ended at: $end_time_formatted"

set elapsed_time [expr {$end_time - $start_time}]
puts "Time to complete all tests: $elapsed_time seconds"


# Interact with the program
interact

